### ISSUE TITLE
Non-conform schema compared to Datacite

### ISSUE THREAD

**Issue by aborel** [UB-LMU/datacite-metadata-generator#4]
Hello,
my team would like to customize the data metadata generator for our own purposes, but first we would like to report a couple of discrepancies with the Datacite documentation that we have observed.
1. awardURI should be an attribute if awardNumber (as explained in https://support.datacite.org/docs/which-metadata-field-in-the-datacite-schema-captures-the-grant-id-information ), whereas the current code makes it a sibling tag
2. The dateInformation field doesn't seem to generate any metadata when one enters input

We will be happy to provide fixes if you accept pull requests, code snippets in this issue or any other way to contribute.

Best regards,
Alain Borel
EPFL Library

**Comment by MSpenger** [comment]
Dear Alain,

sorry for the late reply and thank you for your observations. You are right, we have to adjust the two fields in the generator. 

If you already have a fix, we will happily include a pull request or code snippet here. Otherwise we can also provide the fix in the next days.

It is great to hear that you plan to customize the Metadata Generator for your own purpose. Please let us know if you any more questions or if you want to share your use case with us.

Cheers,
Martin
[forschungsdaten@ub.uni-muenchen.de]

**Comment by madturtles** [comment]
Good morning,
it's my turn to apologize for not answering right away... I think you already have a pending pull request that addresses these issues, but here are my changes just in case:
```
_________awardURI before______
</div>
<input title="awardURI" class="half-width input-field tag-attribute" type="text" placeholder="[AWARD URI]" title="awardURI" value="" />
________ awardURI after ________
<input title="awardURI" class="half-width input-field tag-attribute" type="text" placeholder="[AWARD URI]" title="awardURI" value="" />
_________________________________

______dateInformation before ____
<input class="full-width input-field tag-value" type="text" placeholder="[DATE INFORMATION]" title="dateInformation" value="" />
______ dateInformation after ______
<input class="full-width input-field tag-attribute" type="text" placeholder="[DATE INFORMATION]" title="dateInformation" value="" />
_____________________________________
```

We also noticed a totally unrelated but problematic namespace declaration:
```
--- kernelNamespace before -----
var kernelNamespace = "https://schema.datacite.org/meta/kernel-4.3/";
--- kernelNamespace after -------
var kernelNamespace = "http://datacite.org/schema/kernel-4";
-----------------------------------
```

I will contact you by e-mail for a short description of our use case. I don't have any urgent question at the moment, but I'm sure if will help in the future, in case we need to discuss other topics about the generator.

Thanks for your work!
Alain Borel

**Comment by madturtles** [comment]
Sorry if you got a notification that wasn't making any sense, I keep forgetting how Github is interpreting my input and messing up the code I wanted to show :-D

**Comment by MSpenger** [comment]
Thank you for your feedback and the suggestions. We'll look into the namespace declaration and also add the field for dateInformation.

**Comment by MSpenger** [comment]
The changes are now added.
